import { IServerDomains } from "./models";

/**
 * Pri is Python server
 * Sec is PHP server
 */

export const serverUrlsProd: IServerDomains = {
  't-1c62.com': {
    serverPrimaryUrls: ['https://api.t-1c62.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.t-1c62.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.t-1c62.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.t-1c62.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.t-1c62.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-7801.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-7801.com/api/game-client/v8/',
      'https://api.g-826b.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-7801.com/api/v8/', 'https://api-v4.g-826b.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-7801.com/api/game-client/',
      'https://api-m.g-826b.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-7801.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-7801.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'ely889.com': {
    serverPrimaryUrls: ['https://api.ely889.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.ely889.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.ely889.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.tf-api-ad1e.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.ely889.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-be7c.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-be7c.com/api/game-client/v8/',
      'https://api.t-6d7c.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-be7c.com/api/v8/', 'https://api-v4.t-6d7c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-be7c.com/api/game-client/',
      'https://api-m.t-6d7c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-be7c.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-be7c.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  't-6d7c.com': {
    serverPrimaryUrls: [
      'https://api.t-6d7c.com/api/game-client/v8/',
      'https://api.tf-api-be7c.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.t-6d7c.com/api/v8/', 'https://api-v4.tf-api-be7c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.t-6d7c.com/api/game-client/',
      'https://api-m.tf-api-be7c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.t-6d7c.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.t-6d7c.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'f-1757.com': {
    serverPrimaryUrls: ['https://api.f-1757.com/api/game-client/v8/', 'https://api.i-e83c.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.f-1757.com/api/v8/', 'https://api-v4.i-e83c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.f-1757.com/api/game-client/',
      'https://api-m.i-e83c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.f-1757.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.f-1757.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'g-b38a.com': {
    serverPrimaryUrls: ['https://api.g-b38a.com/api/game-client/v8/', 'https://api.n-2440.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.g-b38a.com/api/v8/', 'https://api-v4.n-2440.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.g-b38a.com/api/game-client/',
      'https://api-m.n-2440.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.g-b38a.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.g-b38a.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'a-777a.com': {
    serverPrimaryUrls: ['https://api.a-777a.com/api/game-client/v8/', 'https://api.g-826b.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.a-777a.com/api/v8/', 'https://api-v4.g-826b.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.a-777a.com/api/game-client/',
      'https://api-m.g-826b.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.a-777a.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.a-777a.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'm-e38f.com': {
    serverPrimaryUrls: ['https://api.m-e38f.com/api/game-client/v8/', 'https://api.t-6d7c.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.m-e38f.com/api/v8/', 'https://api-v4.t-6d7c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.m-e38f.com/api/game-client/',
      'https://api-m.t-6d7c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.m-e38f.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.m-e38f.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'i-e83c.com': {
    serverPrimaryUrls: ['https://api.i-e83c.com/api/game-client/v8/', 'https://api.f-1757.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.i-e83c.com/api/v8/', 'https://api-v4.f-1757.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.i-e83c.com/api/game-client/',
      'https://api-m.f-1757.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.i-e83c.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.i-e83c.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'n-2440.com': {
    serverPrimaryUrls: ['https://api.n-2440.com/api/game-client/v8/', 'https://api.g-b38a.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.n-2440.com/api/v8/', 'https://api-v4.g-b38a.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.n-2440.com/api/game-client/',
      'https://api-m.g-b38a.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.n-2440.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.n-2440.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'g-826b.com': {
    serverPrimaryUrls: ['https://api.g-826b.com/api/game-client/v8/', 'https://api.a-777a.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.g-826b.com/api/v8/', 'https://api-v4.a-777a.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.g-826b.com/api/game-client/',
      'https://api-m.a-777a.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.g-826b.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.g-826b.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-2875.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-2875.com/api/game-client/v8/',
      'https://api.f-1757.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-2875.com/api/v8/', 'https://api-v4.f-1757.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-2875.com/api/game-client/',
      'https://api-m.f-1757.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-2875.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-2875.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-158b.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-158b.com/api/game-client/v8/',
      'https://api.g-b38a.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-158b.com/api/v8/', 'https://api-v4.g-b38a.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-158b.com/api/game-client/',
      'https://api-m.g-b38a.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-158b.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-158b.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-00f6.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-00f6.com/api/game-client/v8/',
      'https://api.a-777a.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-00f6.com/api/v8/', 'https://api-v4.a-777a.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-00f6.com/api/game-client/',
      'https://api-m.a-777a.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-00f6.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-00f6.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-fe4d.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-fe4d.com/api/game-client/v8/',
      'https://api.m-e38f.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-fe4d.com/api/v8/', 'https://api-v4.m-e38f.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-fe4d.com/api/game-client/',
      'https://api-m.m-e38f.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-fe4d.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-fe4d.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-e9dc.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-e9dc.com/api/game-client/v8/',
      'https://api.i-e83c.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-e9dc.com/api/v8/', 'https://api-v4.i-e83c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-e9dc.com/api/game-client/',
      'https://api-m.i-e83c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-e9dc.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-e9dc.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-cc7d.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-cc7d.com/api/game-client/v8/',
      'https://api.n-2440.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-cc7d.com/api/v8/', 'https://api-v4.n-2440.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-cc7d.com/api/game-client/',
      'https://api-m.n-2440.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-cc7d.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-cc7d.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-fdae.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-fdae.com/api/game-client/v8/',
      'https://api.m-e38f.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-fdae.com/api/v8/', 'https://api-v4.m-e38f.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-fdae.com/api/game-client/',
      'https://api-m.m-e38f.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-fdae.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-fdae.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-77c7.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-77c7.com/api/game-client/v8/',
      'https://api.i-e83c.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-77c7.com/api/v8/', 'https://api-v4.i-e83c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-77c7.com/api/game-client/',
      'https://api-m.i-e83c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-77c7.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-77c7.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-9653.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-9653.com/api/game-client/v8/',
      'https://api.n-2440.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-9653.com/api/v8/', 'https://api-v4.n-2440.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-9653.com/api/game-client/',
      'https://api-m.n-2440.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-9653.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-9653.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-953b.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-953b.com/api/game-client/v8/',
      'https://api.g-826b.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-953b.com/api/v8/', 'https://api-v4.g-826b.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-953b.com/api/game-client/',
      'https://api-m.g-826b.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-953b.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-953b.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-e007.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-e007.com/api/game-client/v8/',
      'https://api.m-e38f.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-e007.com/api/v8/', 'https://api-v4.m-e38f.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-e007.com/api/game-client/',
      'https://api-m.m-e38f.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-e007.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-e007.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-8240.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-8240.com/api/game-client/v8/',
      'https://api.i-e83c.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-8240.com/api/v8/', 'https://api-v4.i-e83c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-8240.com/api/game-client/',
      'https://api-m.i-e83c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-8240.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-8240.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-77f2.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-77f2.com/api/game-client/v8/',
      'https://api.n-2440.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-77f2.com/api/v8/', 'https://api-v4.n-2440.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-77f2.com/api/game-client/',
      'https://api-m.n-2440.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-77f2.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-77f2.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-cc83.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-cc83.com/api/game-client/v8/',
      'https://api.g-826b.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-cc83.com/api/v8/', 'https://api-v4.g-826b.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-cc83.com/api/game-client/',
      'https://api-m.g-826b.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-cc83.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-cc83.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-06f9.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-06f9.com/api/game-client/v8/',
      'https://api.m-e38f.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-06f9.com/api/v8/', 'https://api-v4.m-e38f.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-06f9.com/api/game-client/',
      'https://api-m.m-e38f.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-06f9.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-06f9.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-63fa.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-63fa.com/api/game-client/v8/',
      'https://api.i-e83c.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-63fa.com/api/v8/', 'https://api-v4.i-e83c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-63fa.com/api/game-client/',
      'https://api-m.i-e83c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-63fa.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-63fa.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-6118.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-6118.com/api/game-client/v8/',
      'https://api.n-2440.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-6118.com/api/v8/', 'https://api-v4.n-2440.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-6118.com/api/game-client/',
      'https://api-m.n-2440.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-6118.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-6118.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-53fd.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-53fd.com/api/game-client/v8/',
      'https://api.g-826b.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-53fd.com/api/v8/', 'https://api-v4.g-826b.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-53fd.com/api/game-client/',
      'https://api-m.g-826b.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-53fd.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-53fd.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-fa0c.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-fa0c.com/api/game-client/v8/',
      'https://api.m-e38f.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-fa0c.com/api/v8/', 'https://api-v4.m-e38f.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-fa0c.com/api/game-client/',
      'https://api-m.m-e38f.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-fa0c.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-fa0c.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-4ef5.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-4ef5.com/api/game-client/v8/',
      'https://api.i-e83c.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-4ef5.com/api/v8/', 'https://api-v4.i-e83c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-4ef5.com/api/game-client/',
      'https://api-m.i-e83c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-4ef5.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-4ef5.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'f-31c7.com': {
    serverPrimaryUrls: ['https://api.f-31c7.com/api/game-client/v8/', 'https://api.nbde6.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.f-31c7.com/api/v8/', 'https://api-v4.nbde6.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.f-31c7.com/api/game-client/',
      'https://api-m.nbde6.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.f-31c7.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.f-31c7.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'g-609a.com': {
    serverPrimaryUrls: ['https://api.g-609a.com/api/game-client/v8/', 'https://api.a0313.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.g-609a.com/api/v8/', 'https://api-v4.a0313.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.g-609a.com/api/game-client/',
      'https://api-m.a0313.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.g-609a.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.g-609a.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'a-8739.com': {
    serverPrimaryUrls: ['https://api.a-8739.com/api/game-client/v8/', 'https://api.r69c5.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.a-8739.com/api/v8/', 'https://api-v4.r69c5.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.a-8739.com/api/game-client/',
      'https://api-m.r69c5.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.a-8739.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.a-8739.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'hba72.com': {
    serverPrimaryUrls: ['https://api.hba72.com/api/game-client/v8/', 'https://api.t-1c62.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.hba72.com/api/v8/', 'https://api-v4.t-1c62.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.hba72.com/api/game-client/',
      'https://api-m.t-1c62.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.hba72.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.hba72.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'nbde6.com': {
    serverPrimaryUrls: ['https://api.nbde6.com/api/game-client/v8/', 'https://api.f-31c7.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.nbde6.com/api/v8/', 'https://api-v4.f-31c7.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.nbde6.com/api/game-client/',
      'https://api-m.f-31c7.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.nbde6.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.nbde6.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'a0313.com': {
    serverPrimaryUrls: ['https://api.a0313.com/api/game-client/v8/', 'https://api.g-609a.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.a0313.com/api/v8/', 'https://api-v4.g-609a.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.a0313.com/api/game-client/',
      'https://api-m.g-609a.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.a0313.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.a0313.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'r69c5.com': {
    serverPrimaryUrls: ['https://api.r69c5.com/api/game-client/v8/', 'https://api.a-8739.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.r69c5.com/api/v8/', 'https://api-v4.a-8739.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.r69c5.com/api/game-client/',
      'https://api-m.a-8739.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.r69c5.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.r69c5.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'e5046c.com': {
    serverPrimaryUrls: [
      'https://api.e5046c.com/api/game-client/v8/',
      'https://api.tf-api-5c36.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.e5046c.com/api/v8/', 'https://api-v4.tf-api-5c36.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.e5046c.com/api/game-client/',
      'https://api-m.tf-api-5c36.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.e5046c.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.e5046c.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-5c36.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-5c36.com/api/game-client/v8/',
      'https://api.e5046c.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-5c36.com/api/v8/', 'https://api-v4.e5046c.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-5c36.com/api/game-client/',
      'https://api-m.e5046c.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-5c36.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-5c36.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  '24a9f9.com': {
    serverPrimaryUrls: [
      'https://api.24a9f9.com/api/game-client/v8/',
      'https://api.tf-api-c5fd.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.24a9f9.com/api/v8/', 'https://api-v4.tf-api-c5fd.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.24a9f9.com/api/game-client/',
      'https://api-m.tf-api-c5fd.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.24a9f9.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.24a9f9.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'tf-api-c5fd.com': {
    serverPrimaryUrls: [
      'https://api.tf-api-c5fd.com/api/game-client/v8/',
      'https://api.24a9f9.com/api/game-client/v8/',
    ],
    serverSecondaryUrls: ['https://api-v4.tf-api-c5fd.com/api/v8/', 'https://api-v4.24a9f9.com/api/v8/'],
    serverMiniGamePrimaryUrls: [
      'https://api-m.tf-api-c5fd.com/api/game-client/',
      'https://api-m.24a9f9.com/api/game-client/',
    ],
    serverWebsocketUrl: 'wss://ws.tf-api-c5fd.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.tf-api-c5fd.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
  'c-10d6.com': {
    serverPrimaryUrls: ['https://api.c-10d6.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-10d6.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-10d6.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-10d6.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-10d6.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-82e2.com': {
    serverPrimaryUrls: ['https://api.c-82e2.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-82e2.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-82e2.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-82e2.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-82e2.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-6ede.com': {
    serverPrimaryUrls: ['https://api.c-6ede.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-6ede.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-6ede.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-6ede.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-6ede.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-94fe.com': {
    serverPrimaryUrls: ['https://api.c-94fe.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-94fe.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-94fe.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-94fe.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-94fe.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-4ba5.com': {
    serverPrimaryUrls: ['https://api.c-4ba5.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-4ba5.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-4ba5.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-4ba5.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-4ba5.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-98d6.com': {
    serverPrimaryUrls: ['https://api.c-98d6.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-98d6.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-98d6.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-98d6.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-98d6.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-20de.com': {
    serverPrimaryUrls: ['https://api.c-20de.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-20de.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-20de.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-20de.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-20de.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-450a.com': {
    serverPrimaryUrls: ['https://api.c-450a.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-450a.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-450a.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-450a.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-450a.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-a703.com': {
    serverPrimaryUrls: ['https://api.c-a703.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-a703.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-a703.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-a703.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-a703.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-c39f.com': {
    serverPrimaryUrls: ['https://api.c-c39f.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-c39f.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-c39f.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-c39f.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-c39f.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-1da1.com': {
    serverPrimaryUrls: ['https://api.c-1da1.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-1da1.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-1da1.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-1da1.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-1da1.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-476c.com': {
    serverPrimaryUrls: ['https://api.c-476c.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-476c.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-476c.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-476c.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-476c.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-07b1.com': {
    serverPrimaryUrls: ['https://api.c-07b1.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-07b1.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-07b1.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-07b1.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-07b1.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-53dc.com': {
    serverPrimaryUrls: ['https://api.c-53dc.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-53dc.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-53dc.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-53dc.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-53dc.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-e744.com': {
    serverPrimaryUrls: ['https://api.c-e744.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-e744.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-e744.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-e744.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-e744.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-d3f8.com': {
    serverPrimaryUrls: ['https://api.c-d3f8.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-d3f8.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-d3f8.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-d3f8.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-d3f8.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-dbe4.com': {
    serverPrimaryUrls: ['https://api.c-dbe4.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-dbe4.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-dbe4.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-dbe4.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-dbe4.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-5d7a.com': {
    serverPrimaryUrls: ['https://api.c-5d7a.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-5d7a.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-5d7a.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-5d7a.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-5d7a.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-3efe.com': {
    serverPrimaryUrls: ['https://api.c-3efe.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-3efe.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-3efe.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-3efe.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-3efe.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-cf84.com': {
    serverPrimaryUrls: ['https://api.c-cf84.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-cf84.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-cf84.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-cf84.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-cf84.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-bed7.com': {
    serverPrimaryUrls: ['https://api.c-bed7.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-bed7.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-bed7.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-bed7.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-bed7.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-5b44.com': {
    serverPrimaryUrls: ['https://api.c-5b44.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-5b44.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-5b44.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-5b44.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-5b44.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-b0bd.com': {
    serverPrimaryUrls: ['https://api.c-b0bd.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-b0bd.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-b0bd.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-b0bd.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-b0bd.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
  'c-8af0.com': {
    serverPrimaryUrls: ['https://api.c-8af0.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://api-v4.c-8af0.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m.c-8af0.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws.c-8af0.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m.c-8af0.com/',
    serverMaintenanceUrl: 'https://assets.c-dc47.com/sdk/maintenance_minigame.json',
    serverAssetsUrl: 'https://assets.c-dc47.com/',
  },
};

export const serverUrlsDev: IServerDomains = {
  'ely889.com': {
    serverPrimaryUrls: ['https://vx-dev-api.r4espt.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://v4-dev.r4espt.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m-test.r4espt.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws-test.r4espt.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m-test.r4espt.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_test_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
};

export const serverUrlsStaging: IServerDomains = {
  'ely889.com': {
    serverPrimaryUrls: ['https://staging-api.r4espt.com/api/game-client/v8/'],
    serverSecondaryUrls: ['https://v4-staging.r4espt.com/api/v8/'],
    serverMiniGamePrimaryUrls: ['https://api-m-staging.r4espt.com/api/game-client/'],
    serverWebsocketUrl: 'wss://ws-staging.r4espt.com/',
    serverMiniGameWebsocketUrl: 'wss://api-m-staging.r4espt.com/',
    serverMaintenanceUrl: 'https://assets.ae2983.com/sdk/maintenance_test_minigame.json',
    serverAssetsUrl: 'https://assets.ae2983.com/',
  },
};
